### ISSUE TITLE
Mix.Config is deprecated

### ISSUE THREAD

**Issue by fireproofsocks** [MarkHarper/readability#10]
When compiling this package, there is a warning given:

```
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:3
```

The only way I'm aware of to fix this is to replace `use Mix.Config` with `import Config`, but this does mean that the code will no longer be compatible with older versions of Elixir.  Only versions 1.9 and older will be supported with this change, so it would correspond with a major  (?) bump in the version number. (e.g. to v1.0.0 or at least v0.6.0)

**Comment by MarkHarper** [comment]
Should be resolved by #13
