### ISSUE TITLE
Tag v0.6.0; hex release

### ISSUE THREAD

**Issue by fireproofsocks** [MarkHarper/readability#15]
I think the following PRs can be closed now that PR #13 has been merged:

- PR #7 
- PR #10 
- PR #12 

A new version of the package should be released to hex; it would be good to push a Git tag too:

```
git tag v0.6.0
git push --tags
mix hex.publish
```

**Comment by MarkHarper** [comment]
Thanks for reminding me, meant to do this the other day.

**Comment by fireproofsocks** [comment]
Thanks!!
